import "./globals.css";
import local from "next/font/local";

const alhurra = local({
  src: [
    {
      path: "../public/fonts/Alhurra-2020-Regular.ttf",
      weight: "100 400",
    },
    {
      path: "../public/fonts/Alhurra-2020-Bold.ttf",
      weight: "500 900",
    },
  ],
  name: "alhurra",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir={"rtl"}>
      <body className={alhurra.className}>{children}</body>
    </html>
  );
}
